version: '3'
services:
  web:
    image: reynanjolno/basicbidding_web
    ports:
    - "8080:8080"
    environment:
    - endpoints=http://docker.for.mac.host.internal:8081,http://docker.for.mac.host.internal:8082,http://docker.for.mac.host.internal:8083
    - redis.host=redis
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}