version: '3'
services:
  web:
    image: reynanjolno/basicbidding_web
    ports:
    - "8080:8080"
    environment:
    - endpoints=http://host.docker.internal:8081,http://host.docker.internal:8082,http://host.docker.internal:8083 #for mac and windows
    - redis.host=redis
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}